import logging
logger = logging.getLogger('MyL_configurator')
logger.setLevel(logging.DEBUG)
fh = logging.FileHandler('MYL_logs.log')
fh.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.ERROR)
formatter = logging.Formatter('%(asctime)s ; %(name)s ; %(levelname)s ; %(message)s')
ch.setFormatter(formatter)
fh.setFormatter(formatter)
logger.addHandler(ch)
logger.addHandler(fh)
x = 'SERVO'
logger.info(" This procces complited in ;" + x)
logger.error(" There is an error in connection in ; " + x)
logger.critical(" There is an critical error in connection in ; " + x)
logger.debug(" There is an debug error while ; " + x)
logger.warn(" There is an overload while ; " + x)
logger.warning(" There is an deadlock while ; " + x)
logger.exception(" There is an exception while ; " + x)
logger.log(level=2,msg=" Doing smth; " + x)
